export enum OrmModuleConfigProperties {
  ENV_DATABASE_HOST = 'DATABASE_HOST',
  ENV_DATABASE_SCHEMA = 'DATABASE_SCHEMA',
  ENV_DATABASE_USER = 'DATABASE_USER',
  ENV_DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  ENV_DATABASE_PORT = 'DATABASE_PORT',
  ENV_DATABASE_DEBUG = 'DATABASE_DEBUG',
}
