server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /nginx.conf {
    deny all;
    return 404;
  }

  location ~ /(\.git|\.env|nginx\.conf)(/|$) {
    deny all;
    return 404;
  }

  location ~ /\.(?!well-known) {
    deny all;
    access_log off;
    log_not_found off;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
