export enum KeyCloakConfigs {
  ENV_KEYCLOAK_USERS_URI = 'KEYCLOAK_USERS_URI',
  ENV_KEYCLOAK_CONFIGS_URI = 'KEYCLOAK_CONFIGS_URI',
  ENV_KEYCLOAK_USERS_NAME = 'KEYCLOAK_USERS_NAME',
  ENV_KEYCLOAK_USERS_ID = 'KEYCLOAK_USERS_ID',
  ENV_KEYCLOAK_USERS_SECRET = 'KEYCLOAK_USERS_SECRET',
}
