export enum KeyCloakConfigProperties {
  ENV_KEYCLOAK_SERVER_URI = 'KEYCLOAK_SERVER_URI',
  ENV_KEYCLOAK_REALM = 'KEYCLOAK_REALM',
  ENV_KEYCLOAK_CLIENT_ID = 'KEYCLOAK_CLIENT_ID',
  ENV_KEYCLOAK_CLIENT_SECRET = 'KEYCLOAK_CLIENT_SECRET',
}
