export enum KeyCloakConfigProperties {
  ENV_KEYCLOAK_METADATA_URI = 'KEYCLOAK_METADATA_URI',
  ENV_KEYCLOAK_CLIENT_ID = 'KEYCLOAK_CLIENT_ID',
  ENV_KEYCLOAK_CLIENT_SECRET = 'KEYCLOAK_CLIENT_SECRET',
  ENV_KEYCLOAK_USERS_URI = 'KEYCLOAK_USERS_URI',
  ENV_KEYCLOAK_USERS_ID = 'KEYCLOAK_USERS_ID',
}
