export enum KeyCloakConfigProperties {
  ENV_KEYCLOAK_SERVER_URI = 'KEYCLOAK_SERVER_URI',
  ENV_KEYCLOAK_REALM = 'KEYCLOAK_REALM',
  ENV_KEYCLOAK_PUBLIC_CLIENT_ID = 'KEYCLOAK_PUBLIC_CLIENT_ID',
  ENV_KEYCLOAK_PUBLIC_CLIENT_SECRET = 'KEYCLOAK_PUBLIC_CLIENT_SECRET',
  ENV_KEYCLOAK_ADMIN_CLIENT_ID = 'KEYCLOAK_ADMIN_CLIENT_ID',
  ENV_KEYCLOAK_ADMIN_CLIENT_SECRET = 'KEYCLOAK_ADMIN_CLIENT_SECRET',
}
