server {
    server_name nl-bc.dev.sogoservices.com;
    root /var/www/html;

    include /etc/nginx/default.d/*.conf;

    # Block access to nginx configuration and other sensitive files.
    location = /nginx.conf {
        deny all;
        return 404;
    }

    location ~ /(?:\.|.*\.(?:conf|ini|log|env|bak|swp|git|htaccess))$ {
        deny all;
        return 404;
    }

    location ~ /(?:^|/)\.[^/]+$ {
        deny all;
        return 404;
    }

    location / {
        autoindex off;
        try_files $uri $uri/ /index.html =404;
    }

    location /api {
        proxy_pass http://nodejs:3000;
    }

    location /swagger {
        proxy_pass http://nodejs:3000;
    }

    location /put.raw {
        rewrite put.raw /api/file/raw?path=./gil.txt break;
        proxy_pass http://nodejs:3000;
    }

    error_page 404 /404.html;
    location = /404.html {
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
    }

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/nginx/keys/bc_public.crt;
    ssl_certificate_key /etc/nginx/keys/bc_private.key;
}
