export enum AuthModuleConfigProperties {
  ENV_JWT_PRIVATE_KEY_LOCATION = 'JWT_PRIVATE_KEY_LOCATION',
  ENV_JWT_PUBLIC_KEY_LOCATION = 'JWT_PUBLIC_KEY_LOCATION',
  ENV_JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  ENV_JWT_CONFIGS_URI = 'JWT_CONFIGS_URI',
  ENV_JWK_PRIVATE_KEY_LOCATION = 'JWK_PRIVATE_KEY_LOCATION',
  ENV_JWK_PUBLIC_KEY_LOCATION = 'JWK_PUBLIC_KEY_LOCATION',
  ENV_JWK_PUBLIC_JSON = 'JWK_PUBLIC_JSON',
  ENV_JKU_URL = 'JKU_URL',
  ENV_X5U_URL = 'X5U_URL',
}
