export enum AuthModuleConfigProperties {
  ENV_JWT_PRIVATE_KEY_LOCATION = 'JWT_PRIVATE_KEY_LOCATION',
  ENV_JWT_PUBLIC_KEY_LOCATION = 'JWT_PUBLIC_KEY_LOCATION',
  ENV_JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  ENV_JWT_CONFIGS_URI = 'JWT_CONFIGS_URI',
}
